language: python

python:
- '2.7'
- '3.6'

install:
- pip install -r requirements_dev.txt
- pip install .

script:
- pytest
- make docsrun

deploy:
- provider: pages
  skip_cleanup: true
  local_dir: "./docs/_build/html"
  github_token:
    secure: "PJVAhUT3o9u9nfhkM84Ya8gVPg2v8xUIcTrhYo4rnPw8PmzVQ7x582b4M2SqqWAkrcMn7uycbbaoGzNp1UFLwUo6xMJgqAXRZMh6EQwPidhZBOzkE2FyjWHC26HxRWOk+5RtOopj0TsGcpXsCVn9uBtC3wCN1kdSZ+s59ah3Au8zDT9wOIM7AosLCMtyimZy1TWxQUBoN5y94KUzmBQk3ZaEoPN2B3wi19mdyuMOoUFJJVcblhfpZeS1BqEawt6U8mEhgiSKobmZMFngP3Le1kSR9mzqMyZQxvcqTxkRLQd0qouU39/FktMKrFfqvGXkqXcSVOAldnzwCxblaPQB2WcBCs9fvkkkewB9bvUAIBBAGLjewp5/m82hZfzwiqB5C8r0H2WskO28H0RUxOwMButesDRNHuKlQuidWhWV2WJOzuA7lp/IBMU6L8ue5zcd/39fpCf0vqE5DU5V2Pz+y5t61yrseIuw3ZjyYc8kJK/m7t98HScKpsKD/24yRCpWmQsCKr1Y/ywvNS9nd5HH9s6UBH99UE9NJzpkcKa72B6Iww82r7wPJ5F8LJ1sryo1XXiGtYoiADXs3wgkWNfc1Zm7FEO+JIzWBochDybDOof0YcbxjU/6OSwYXIXxQejRyT9eXyRJRTbW8CIfCXdXrK/U2CCUXkNqVuCoTM/m4Cw="
  keep_history: true
  on:
    branch: docsdeploy 
    python: "3.6"
