language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest
  - make docsrun

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: ./docs/_build/html
    github_token:
      secure: "notyet"
    keep_history: true
    on:
      branch: master
