language: python

python:
- '2.7'
- '3.6'

install:
- pip install -r requirements_dev.txt
- pip install .

script:
- pytest
- make docsrun

deploy:
- provider: pages
  skip_cleanup: true
  local_dir: "./docs/_build/html"
  github_token:
    secure: "ib14t8x8K33OPQKeya9InVscSHTn4tfXSjEXwXIWia7K/Y2Rt2xzXMbF9dYktJ8kaohpLwGX1cdWY6FR08xah59NGCVCY0KFYOj/G2voNAoqwzkZEgEbCTbOcVTh/3996s17MjK3ul0uk8g8cxqQZM2r97SKaIsne1mJ72FaZ2rHxdzYRGhEe19/GHQhz3GA2p7TDKqAS9x+5LSwFhknAANdQNnc9Cw9HwPGCjZO0/VwLx0Qbery02y7ypngiGJ7j+2BG4r2N+qBq1zWJfi4Lfn7AiY1bypVu3NmKcInJcALrAv28Qx7Zd+UfbGXxnGkQRwm3GQdbJ2jdQpVe8++dFiuNBeXl8B7fNC5D8C9K1kzUD2bo+cZ3CS2gqN7VXNySvpXOBpr4xNd3mrQr3Y15CmSdx+QjIE6sDe9A/7tI0WzA2zERde21sTe8muPTFSlJ5lHnAlNE0W7w6mSwYZwrIKOR+DoOxc6vjzmt8I1TDVHslYFYaFs90aQabBCkxGF/EQ5UhFT+8dOeWrRNdmGCSQLakyww659GmZXC1+LVeAwRTF7M9By6yH2duLwVC9jxavaEv5OWWpOVbMZ47iff6or5kRZXo1m04lz6sOVrtI9+ecYJ2yhx35qv5q1ZNG3l67JrId5e+IOiXycujcwyqLnIV96L0+3RKs9Znn+BQY="
  keep_history: true
  on:
    branch: docsdeploy 
    python: "3.6"
